jwt:
  secret:
    key: your-base64-encoded-secret-key

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB-name
    username: root
    password: your-DB-password

  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경 기준
    show-sql: true
    properties:
      hibernate:
        format_sql: true